	<footer>
   		<div class="container pb-3">
   			<div class="row">
   				<div class="row col-4">
	   				<div>
						<img id="imgLg" src="anh/logo1.png">
					</div>
					<div>
						<h3 class="pt-4 text-light">LACVIET<span class="text-success">.com</span></h3>
						<p class="text-info"><i>Nhớ về cội nguồn dân tộc</i></p>
					</div>
	   			</div>
	   			<div class="col-5 row mt-4 text-light">
	   				<div class="col-6">
	   					<h3 class="text-info">Thể loại</h3>
	   					<li><a href="#" title="">Thần thoại</a></li>
	   					<li><a href="#" title="">Giả sử</a></li>
	   					<li><a href="#" title="">Tiểu sử</a></li>
	   					<li><a href="#" title="">Truyện tranh</a></li>
	   				</div>
	   				<div class="col-6">
	   					<h3 class="text-info">Triều đại</h3>
	   					<li><a href="#" title="">Nhà Đinh</a></li>
	   					<li><a href="#" title="">Nhà Lý</a></li>
	   					<li><a href="#" title="">Nhà Trần</a></li>
	   				</div>
	   			</div>
	   			<div class="col-3 mt-4">
   					<h3 class="text-info">Thông tin liên hệ</h3>
   					<li class="text-light">Email: <a href="tien.nv.59cntt@ntu.edu.vn" title="">tien.nv.59cntt@ntu.edu.vn</a></li>
   					<li class="text-light">Số điện thoại: <a href="0981530459">0981530459</a></li>
   				</div>
   			</div>
   		</div>
    </footer>
    <div class="bg-dark text-center">
		<p>Copyright © 2020 Thiết kể bởi <b><a class="text-success" href="#">Nguyễn Văn Tiến</a></b></p>
	</div>
	<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
</body>
</html>